[package]
name = "rust_deploy"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
solana-sdk = "2.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bs58 = "0.5"
base64 = "0.21"
solana-program = "2.3.0"
spl-token = "8.0.0"
